$primary_paletteKeyColor = 61afef
$secondary_paletteKeyColor = 56b6c2
$tertiary_paletteKeyColor = e5c07b
$neutral_paletteKeyColor = 5c6370
$neutral_variant_paletteKeyColor = 4b5263

$background = 282c34
$onBackground = e6e9ef

$surface = 282c34
$surfaceDim = 21252b
$surfaceBright = 393e48
$surfaceContainerLowest = 1e2228
$surfaceContainerLow = 21252b
$surfaceContainer = 2c313c
$surfaceContainerHigh = 31353f
$surfaceContainerHighest = 393e48
$onSurface = e6e9ef

$surfaceVariant = 3b4048
$onSurfaceVariant = 979eab

$inverseSurface = e6e9ef
$inverseOnSurface = 282c34

$outline = 5c6370
$outlineVariant = 4b5263
$shadow = 000000
$scrim = 000000

$surfaceTint = 61afef
$primary = 61afef
$onPrimary = 1f2430
$primaryContainer = 2f5f95
$onPrimaryContainer = e6f1ff
$inversePrimary = 8fc7ff

$secondary = 56b6c2
$onSecondary = 1f2428
$secondaryContainer = 2d5960
$onSecondaryContainer = dffbff

$tertiary = e5c07b
$onTertiary = 2e2618
$tertiaryContainer = 6b5731
$onTertiaryContainer = fff2d6

$error = e06c75
$onError = 2b1b1d
$errorContainer = 6e2e35
$onErrorContainer = ffe1e4

$primaryFixed = 9fd0ff
$primaryFixedDim = 61afef
$onPrimaryFixed = 11161d
$onPrimaryFixedVariant = 2f5f95

$secondaryFixed = 8ed7df
$secondaryFixedDim = 56b6c2
$onSecondaryFixed = 111618
$onSecondaryFixedVariant = 2d5960

$tertiaryFixed = f3d29a
$tertiaryFixedDim = e5c07b
$onTertiaryFixed = 1b160d
$onTertiaryFixedVariant = 6b5731

$term0 = 282c34
$term1 = e06c75
$term2 = 98c379
$term3 = e5c07b
$term4 = 61afef
$term5 = be5046
$term6 = 56b6c2
$term7 = 979eab
$term8 = 393e48
$term9 = d19a66
$term10 = 56b6c2
$term11 = e5c07b
$term12 = 61afef
$term13 = be5046
$term14 = 56b6c2
$term15 = abb2bf

$rosewater = e6e9ef
$flamingo = d19a66
$pink = c678dd
$mauve = c678dd
$red = e06c75
$maroon = be5046
$peach = d19a66
$yellow = e5c07b
$green = 98c379
$teal = 56b6c2
$sky = 7bcbd6
$sapphire = 61afef
$blue = 61afef
$lavender = abb2bf

$text = e6e9ef
$subtext1 = abb2bf
$subtext0 = 979eab
$overlay2 = 7f8793
$overlay1 = 6b7280
$overlay0 = 5c6370

$surface2 = 4b5263
$surface1 = 3b4048
$surface0 = 31353f
$base = 282c34
$mantle = 21252b
$crust = 1e2228

$success = 98c379
$onSuccess = 1d2718
$successContainer = 3d4d33
$onSuccessContainer = e8ffd7